title = "Configuration sur-mesure Gitleaks"

# NOUVEAU : On dit à Gitleaks de garder ses règles par défaut !
[extend]
useDefault = true

# ----------------------------------------------------------------------
# RÈGLE 1 : Détection des mots de passe de base de données génériques
# ----------------------------------------------------------------------
[[rules]]
id = "custom-db-password-leak"
description = "Détection d'une affectation de mot de passe en clair (ex: DB_PASSWORD = '...')"
regex = '''(?i)(?:db_password|db_pass|database_password)\s*=\s*['"][^'"]+['"]'''
tags = ["password", "database", "custom-rule"]
