name: Zero-Trust Secret Scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  secret-scanning:
    name: Gitleaks Full Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code avec historique
        uses: actions/checkout@v4
        with:
          # CRITIQUE : Sans ce "0", Git ne télécharge que le dernier commit !
          fetch-depth: 0

      - name: Scan de tout l'historique avec Gitleaks (Règles Custom)
        run: |
          echo "Lancement de l'audit avec notre fichier gitleaks.toml..."
          docker run --rm -v ${{ github.workspace }}:/code zricethezav/gitleaks:latest detect --source="/code" -c="/code/gitleaks.toml" -v
