name: Zero-Trust Secret Scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  secret-scanning:
    name: Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Toujours indispensable pour avoir l'historique

      # NOUVELLE ÉTAPE : Appel direct du conteneur Docker Gitleaks
      - name: Audit complet de l'historique (Mode Detect)
        uses: docker://zricethezav/gitleaks:latest
        with:
          # Ici, Docker accepte nos arguments et va scanner tout le dossier de travail !
          args: detect --source /github/workspace --verbose
